# nginx 기반 이미지 사용
FROM nginx:alpine

# 기본 nginx 설정 파일 제거
RUN rm /etc/nginx/conf.d/default.conf

# 커스텀 nginx 설정 파일 복사
COPY default.conf /etc/nginx/conf.d/

# 웹 파일들을 nginx 기본 디렉토리로 복사
COPY src/ /usr/share/nginx/html/

# nginx 포트 노출
# ---- 여기에 코드를 추가하세요
# 1. 컨테이너의 외부 노출 포트에 대한 META 정보를 노출하세요 (80 포트)
# 2. 컨테이너를 실행시 처음 실행되는 프로세스 명령어를 
#    CMD를 이용해서 nginx -g daemon off 를 실행
