FROM ubuntu:24.04

RUN apt-get update && apt-get install -y openjdk-21-jdk \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV SPRING_PROFILES_ACTIVE=local

COPY target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
