# ── 빌드 스테이지 ────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ── 배포 스테이지 ─────────────────────────────
FROM nginx:alpine

# 여기에 builder stage에서 생성한 Html, CSS, JS Static Resource를 
# default.conf에서 설정하고 있는 /usr/share/nginx/html 아래 복사하기

CMD ["nginx", "-g", "daemon off;"]
